In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rc('font', family='NanumBarunGothic') # 혹은 다른 설치한 Nanum 폰트 사용
import scipy
import scipy.stats as stats
import pickle

## 연도별 커뮤니티 게시글 토픽 확인

### 데이터 전처리 

In [2]:
df_dcinside = pd.read_csv("./teamkim_datas.SNS_DCinside.csv")
df_helpline = pd.read_csv("./teamkim_datas.SNS_helpline.csv")
df_naver_symptom = pd.read_csv("./teamkim_datas.SNS_naver_kin_symptom.csv")

df_dcinside["date"] = pd.to_datetime(df_dcinside["date"]).dt.strftime("%Y")
df_helpline["date"] = pd.to_datetime(df_helpline["date"]).dt.strftime("%Y")
df_naver_symptom['question_datetime'] = df_naver_symptom['question_datetime'].str.replace('작성일\\n', '').str.strip()
# "조회수"라는 값이 포함되어있는 행을 모두 지우는 코드
df_naver_symptom = df_naver_symptom[~df_naver_symptom['question_datetime'].str.contains('조회수')]
df_naver_symptom['question_datetime'] = pd.to_datetime(df_naver_symptom['question_datetime']).dt.strftime("%Y")
df_naver_symptom = df_naver_symptom.reset_index()

df_dcinside.replace(np.nan, '', inplace=True)
df_helpline.replace(np.nan, '', inplace=True)
df_naver_symptom.replace(np.nan, '', inplace=True)

dc_2020_title = df_dcinside.query("date == '2020'")["title"].to_list()
dc_2020_contents = df_dcinside.query("date == '2020'")["contents"].to_list()
list_dc_2020 = dc_2020_title + dc_2020_contents
helpline_2020_title = df_helpline.query("date == '2020'")["title_disease"].to_list()
helpline_2020_post = df_helpline.query("date == '2020'")["post_contents"].to_list()
helpline_2020_reply = df_helpline.query("date == '2020'")["reply_contents"].to_list()
list_helpline_2020 = helpline_2020_title + helpline_2020_post + helpline_2020_reply
naver_2020_title = df_naver_symptom.query("question_datetime == '2020'")["question_title"].to_list()
naver_2020_question = df_naver_symptom.query("question_datetime == '2020'")["question_content"].to_list()
naver_2020_answer = df_naver_symptom.query("question_datetime == '2020'")["answer1_content"].to_list()
list_naver_2020 = naver_2020_title + naver_2020_question + naver_2020_answer

dc_2022_title = df_dcinside.query("date == '2022'")["title"].to_list()
dc_2022_contents = df_dcinside.query("date == '2022'")["contents"].to_list()
list_dc_2022 = dc_2022_title + dc_2022_contents
helpline_2022_title = df_helpline.query("date == '2022'")["title_disease"].to_list()
helpline_2022_post = df_helpline.query("date == '2022'")["post_contents"].to_list()
helpline_2022_reply = df_helpline.query("date == '2022'")["reply_contents"].to_list()
list_helpline_2022 = helpline_2022_title + helpline_2022_post + helpline_2022_reply
naver_2022_title = df_naver_symptom.query("question_datetime == '2022'")["question_title"].to_list()
naver_2022_question = df_naver_symptom.query("question_datetime == '2022'")["question_content"].to_list()
naver_2022_answer = df_naver_symptom.query("question_datetime == '2022'")["answer1_content"].to_list()
list_naver_2022 = naver_2022_title + naver_2022_question + naver_2022_answer

dc_2023_title = df_dcinside.query("date == '2023'")["title"].to_list()
dc_2023_contents = df_dcinside.query("date == '2023'")["contents"].to_list()
list_dc_2023 = dc_2023_title + dc_2023_contents
helpline_2023_title = df_helpline.query("date == '2023'")["title_disease"].to_list()
helpline_2023_post = df_helpline.query("date == '2023'")["post_contents"].to_list()
helpline_2023_reply = df_helpline.query("date == '2023'")["reply_contents"].to_list()
list_helpline_2023 = helpline_2023_title + helpline_2023_post + helpline_2023_reply
naver_2023_title = df_naver_symptom.query("question_datetime == '2023'")["question_title"].to_list()
naver_2023_question = df_naver_symptom.query("question_datetime == '2023'")["question_content"].to_list()
naver_2023_answer = df_naver_symptom.query("question_datetime == '2023'")["answer1_content"].to_list()
list_naver_2023 = naver_2023_title + naver_2023_question + naver_2023_answer

dc_2024_title = df_dcinside.query("date == '2024'")["title"].to_list()
dc_2024_contents = df_dcinside.query("date == '2024'")["contents"].to_list()
list_dc_2024 = dc_2024_title + dc_2024_contents
helpline_2024_title = df_helpline.query("date == '2024'")["title_disease"].to_list()
helpline_2024_post = df_helpline.query("date == '2024'")["post_contents"].to_list()
helpline_2024_reply = df_helpline.query("date == '2024'")["reply_contents"].to_list()
list_helpline_2024 = helpline_2024_title + helpline_2024_post + helpline_2024_reply
naver_2024_title = df_naver_symptom.query("question_datetime == '2024'")["question_title"].to_list()
naver_2024_question = df_naver_symptom.query("question_datetime == '2024'")["question_content"].to_list()
naver_2024_answer = df_naver_symptom.query("question_datetime == '2024'")["answer1_content"].to_list()
list_naver_2024 = naver_2024_title + naver_2024_question + naver_2024_answer

list_2020 = list_dc_2020 + list_helpline_2020 + list_naver_2020
list_2022 = list_dc_2022 + list_helpline_2022 + list_naver_2022
list_2023 = list_dc_2023 + list_helpline_2023 + list_naver_2023
list_2024 = list_dc_2024 + list_helpline_2024 + list_naver_2024

### 토픽확인

In [3]:
# 불용어 리스트 생성 (예시)
stopwords = ['가', '고', '을', '를', '이', '는']
from konlpy.tag import Okt

# Okt 형태소 분석기 인스턴스 생성
okt = Okt()

# 토크나이징 함수 정의
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=stopwords):
    return [
        word for word, tag in okt.pos(
            raw, 
            norm=True,   
            stem=True    
            )
            if len(word) > 1 and tag in pos and word not in stopword

    ]

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(tokenizer=tokenizer, use_idf=True)
features = vectorizer.fit_transform(list_2020)
features.toarray()

/usr/local/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=5, random_state=55) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features) #교육

LatentDirichletAllocation(n_components=5, random_state=55)

In [6]:
dictionary_list = vectorizer.get_feature_names_out()

In [7]:
lda_model.components_

array([[0.2711301 , 0.24998505, 0.24998505, ..., 0.34604986, 0.20496074,
        0.21044142],
       [0.2000291 , 0.20002511, 0.20002511, ..., 0.61880971, 1.50176166,
        0.2833907 ],
       [0.20002808, 0.20002503, 0.20002503, ..., 0.20005852, 0.20005525,
        0.20004637],
       [0.20002787, 0.20002631, 0.20002631, ..., 0.20005708, 0.24653363,
        0.20004409],
       [0.20002914, 0.2000258 , 0.2000258 , ..., 0.20006142, 0.20005718,
        0.41352811]])

In [8]:
topics_output = lda_model.transform(features)
df_topics_score = pd.DataFrame(data=topics_output)

In [9]:
df_topics_score['dominant_topic_number'] = np.argmax(topics_output, axis=1) #  "topics_output" 배열에서 각 행마다 최대값의 인덱스를 찾아 "dominant_topic_number" 열에 할당

In [10]:
df_topics_score['sentences'] = list_2020

In [11]:
df_topics_score

0         1         2         3         4  dominant_topic_number  \
0    0.052666  0.796152  0.050399  0.050392  0.050391                      1   
1    0.054961  0.054972  0.779806  0.055113  0.055148                      2   
2    0.082853  0.082870  0.668536  0.082869  0.082871                      2   
3    0.061305  0.059884  0.060031  0.757398  0.061382                      3   
4    0.696284  0.075927  0.075937  0.075924  0.075927                      0   
..        ...       ...       ...       ...       ...                    ...   
417  0.891361  0.027159  0.027159  0.027163  0.027158                      0   
418  0.912125  0.021968  0.021963  0.021986  0.021958                      0   
419  0.067500  0.067636  0.067400  0.730054  0.067410                      3   
420  0.040168  0.037861  0.037531  0.846871  0.037569                      3   
421  0.137895  0.022961  0.022569  0.794001  0.022574                      3   

                                             sentences  
0                   안락사&존엄사 관련 인권단체를 만들기 위해 카페를 개설했습니다  
1                              저칼륨혈증 주기성 사지마비(feat 꾀병)  
2                                         쇼그렌은 언급 1도없네  
3                          유전병 게이들아 드디어 유전자가위가 상용화 된단다  
4                                     나보다 희귀한 질병인애 있냐?  
..                                                 ...  
417  안녕하세요?\n \n온라인 상담실을 통해 문의하신 내용에 대해 답변드립니다.\n\n...  
418  안녕하세요?\n1:1 상담을 통해 문의하신 문의사항에 대해 답변 드립니다.\n「희귀...  
419                                  통풍 초기증상 좋은음식 있나요?  
420  통풍 초기증상 좋은음식 있나요??\n얼마전 종합건강검진에서 제 남편이 통풍수치가 높...  
421  통풍은 아플통 ,바람풍 한자를쓸정도로 바람만불어도 아프다라고 할정도로 통증이 엄청심...  

[422 rows x 7 columns]

In [12]:
## 상위 단어 추출
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T #T는 행과 열을 바꿈
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:10])# 시리즈 형식으로 출력 get values from series / index
    print(topics_text)
    topics_list.append(topics_text)


topics_list_add = [topics_list, ['Topic0', 'Topic1', 'Topic2', 'Topic3', 'Topic4']]
df_topics_keywords_2020 = pd.DataFrame(topics_list_add)
df_topics_keywords_2020

하다 희귀질환 질환 의료 산정 지원 특례 되다 사업 기준
하다 이유 힘내다 병원 카페 종증 검사 만들다 심근병증 확장
섬유화 하다 병원 오다 증후군 질환 치료법 로스 엘러스 뇌낭종
하다 병원 투석 체트 질환 소아 크론병 지방 거점 말기
개다 의약품 신경섬유 먹다 하다 51 병증 공동 95.0 사람


0                                  1  \
0  하다 희귀질환 질환 의료 산정 지원 특례 되다 사업 기준  하다 이유 힘내다 병원 카페 종증 검사 만들다 심근병증 확장   
1                           Topic0                             Topic1   

                                    2                               3  \
0  섬유화 하다 병원 오다 증후군 질환 치료법 로스 엘러스 뇌낭종  하다 병원 투석 체트 질환 소아 크론병 지방 거점 말기   
1                              Topic2                          Topic3   

                                    4  
0  개다 의약품 신경섬유 먹다 하다 51 병증 공동 95.0 사람  
1                              Topic4

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(tokenizer=tokenizer, use_idf=True)
features = vectorizer.fit_transform(list_2022)
features.toarray()

/usr/local/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=5, random_state=55) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features) #교육

LatentDirichletAllocation(n_components=5, random_state=55)

In [15]:
dictionary_list = vectorizer.get_feature_names_out()
topics_output = lda_model.transform(features)
df_topics_score = pd.DataFrame(data=topics_output)
df_topics_score['dominant_topic_number'] = np.argmax(topics_output, axis=1) #  "topics_output" 배열에서 각 행마다 최대값의 인덱스를 찾아 "dominant_topic_number" 열에 할당
df_topics_score['sentences'] = list_2022
## 상위 단어 추출
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T #T는 행과 열을 바꿈
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:10])# 시리즈 형식으로 출력 get values from series / index
    print(topics_text)
    topics_list.append(topics_text)


topics_list_add = [topics_list, ['Topic0', 'Topic1', 'Topic2', 'Topic3', 'Topic4']]
df_topics_keywords_2022 = pd.DataFrame(topics_list_add)
df_topics_keywords_2022

신경섬유 화이팅 먹다 종인 로스 화증 다발 증후군 종양 scid
죽다 때문 진짜 신경섬유 살다 보다 하다 증후군 희귀 종증
진짜 사람 하다 의료행위 신경섬유 증인 자다 질환 받다 발성
먹다 간질 싶다 폐암 씨발 신생아 기형 신경 모야 유종
하다 희귀질환 질환 의료 되다 특례 산정 지원 사업 등록


0                                 1  \
0  신경섬유 화이팅 먹다 종인 로스 화증 다발 증후군 종양 scid  죽다 때문 진짜 신경섬유 살다 보다 하다 증후군 희귀 종증   
1                               Topic0                            Topic1   

                                   2                               3  \
0  진짜 사람 하다 의료행위 신경섬유 증인 자다 질환 받다 발성  먹다 간질 싶다 폐암 씨발 신생아 기형 신경 모야 유종   
1                             Topic2                          Topic3   

                                 4  
0  하다 희귀질환 질환 의료 되다 특례 산정 지원 사업 등록  
1                           Topic4

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(tokenizer=tokenizer, use_idf=True)
features = vectorizer.fit_transform(list_2023)
features.toarray()

/usr/local/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=5, random_state=55) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features) #교육

LatentDirichletAllocation(n_components=5, random_state=55)

In [18]:
dictionary_list = vectorizer.get_feature_names_out()
topics_output = lda_model.transform(features)
df_topics_score = pd.DataFrame(data=topics_output)
df_topics_score['dominant_topic_number'] = np.argmax(topics_output, axis=1) #  "topics_output" 배열에서 각 행마다 최대값의 인덱스를 찾아 "dominant_topic_number" 열에 할당
df_topics_score['sentences'] = list_2023
## 상위 단어 추출
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T #T는 행과 열을 바꿈
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:10])# 시리즈 형식으로 출력 get values from series / index
    print(topics_text)
    topics_list.append(topics_text)


topics_list_add = [topics_list, ['Topic0', 'Topic1', 'Topic2', 'Topic3', 'Topic4']]
df_topics_keywords_2023 = pd.DataFrame(topics_list_add)
df_topics_keywords_2023

증상 하다 협착증 사람 생각 무슨 되다 식도염 아토피 역류성
app official dc 무릎 씨발 증후군 증상 진짜 마비 카페
하다 희귀질환 질환 되다 의료 지원 증상 치료 사업 검사
증상 하다 여기 심의 검토 수준 혈뇨 희귀 질환 질병
증상 하다 디스크 초기 허리 임신 들다 생리 코로나 독감


0                                      1  \
0  증상 하다 협착증 사람 생각 무슨 되다 식도염 아토피 역류성  app official dc 무릎 씨발 증후군 증상 진짜 마비 카페   
1                             Topic0                                 Topic1   

                                 2                              3  \
0  하다 희귀질환 질환 되다 의료 지원 증상 치료 사업 검사  증상 하다 여기 심의 검토 수준 혈뇨 희귀 질환 질병   
1                           Topic2                         Topic3   

                                 4  
0  증상 하다 디스크 초기 허리 임신 들다 생리 코로나 독감  
1                           Topic4

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(tokenizer=tokenizer, use_idf=True)
features = vectorizer.fit_transform(list_2024)
features.toarray()

/usr/local/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=5, random_state=55) #인스턴스화 #n_components 토픽의 갯수
lda_model.fit(features) #교육

LatentDirichletAllocation(n_components=5, random_state=55)

In [21]:
dictionary_list = vectorizer.get_feature_names_out()
topics_output = lda_model.transform(features)
df_topics_score = pd.DataFrame(data=topics_output)
df_topics_score['dominant_topic_number'] = np.argmax(topics_output, axis=1) #  "topics_output" 배열에서 각 행마다 최대값의 인덱스를 찾아 "dominant_topic_number" 열에 할당
df_topics_score['sentences'] = list_2024
## 상위 단어 추출
topics_list = list()
for topic in lda_model.components_:
    df_datas = [topic, dictionary_list]
    df_topics = pd.DataFrame(data=df_datas)
    df_topics= df_topics.T #T는 행과 열을 바꿈
    df_topics = df_topics.sort_values(0, ascending=False)
    # print(df_topics[:3])
    topics_text = ' '.join(df_topics[1].values[:10])# 시리즈 형식으로 출력 get values from series / index
    print(topics_text)
    topics_list.append(topics_text)


topics_list_add = [topics_list, ['Topic0', 'Topic1', 'Topic2', 'Topic3', 'Topic4']]
df_topics_keywords_2024 = pd.DataFrame(topics_list_add)
df_topics_keywords_2024

하다 증상 희귀질환 되다 질환 의료 받다 지원 사업 통증
극복 대장암 증상 무슨 혹시 유종 증후군 스타우트 고함 539
증상 전립선비대증 증후군 초기 생리 위염 이다 폐암 리스트 병원
증상 독감 초기 코로나 맞다 전립선염 위암 두피 공황 몸살
증상 불안장애 질병 마비 공황장애 순환 생명 복의 퍼옴 습진


0                                   1  \
0  하다 증상 희귀질환 되다 질환 의료 받다 지원 사업 통증  극복 대장암 증상 무슨 혹시 유종 증후군 스타우트 고함 539   
1                           Topic0                              Topic1   

                                     2                                 3  \
0  증상 전립선비대증 증후군 초기 생리 위염 이다 폐암 리스트 병원  증상 독감 초기 코로나 맞다 전립선염 위암 두피 공황 몸살   
1                               Topic2                            Topic3   

                                   4  
0  증상 불안장애 질병 마비 공황장애 순환 생명 복의 퍼옴 습진  
1                             Topic4

### 분석결과

In [22]:
df_topics_keywords_2020

0                                  1  \
0  하다 희귀질환 질환 의료 산정 지원 특례 되다 사업 기준  하다 이유 힘내다 병원 카페 종증 검사 만들다 심근병증 확장   
1                           Topic0                             Topic1   

                                    2                               3  \
0  섬유화 하다 병원 오다 증후군 질환 치료법 로스 엘러스 뇌낭종  하다 병원 투석 체트 질환 소아 크론병 지방 거점 말기   
1                              Topic2                          Topic3   

                                    4  
0  개다 의약품 신경섬유 먹다 하다 51 병증 공동 95.0 사람  
1                              Topic4

In [23]:
df_topics_keywords_2022

0                                 1  \
0  신경섬유 화이팅 먹다 종인 로스 화증 다발 증후군 종양 scid  죽다 때문 진짜 신경섬유 살다 보다 하다 증후군 희귀 종증   
1                               Topic0                            Topic1   

                                   2                               3  \
0  진짜 사람 하다 의료행위 신경섬유 증인 자다 질환 받다 발성  먹다 간질 싶다 폐암 씨발 신생아 기형 신경 모야 유종   
1                             Topic2                          Topic3   

                                 4  
0  하다 희귀질환 질환 의료 되다 특례 산정 지원 사업 등록  
1                           Topic4

In [24]:
df_topics_keywords_2023

0                                      1  \
0  증상 하다 협착증 사람 생각 무슨 되다 식도염 아토피 역류성  app official dc 무릎 씨발 증후군 증상 진짜 마비 카페   
1                             Topic0                                 Topic1   

                                 2                              3  \
0  하다 희귀질환 질환 되다 의료 지원 증상 치료 사업 검사  증상 하다 여기 심의 검토 수준 혈뇨 희귀 질환 질병   
1                           Topic2                         Topic3   

                                 4  
0  증상 하다 디스크 초기 허리 임신 들다 생리 코로나 독감  
1                           Topic4

In [25]:
df_topics_keywords_2024

0                                   1  \
0  하다 증상 희귀질환 되다 질환 의료 받다 지원 사업 통증  극복 대장암 증상 무슨 혹시 유종 증후군 스타우트 고함 539   
1                           Topic0                              Topic1   

                                     2                                 3  \
0  증상 전립선비대증 증후군 초기 생리 위염 이다 폐암 리스트 병원  증상 독감 초기 코로나 맞다 전립선염 위암 두피 공황 몸살   
1                               Topic2                            Topic3   

                                   4  
0  증상 불안장애 질병 마비 공황장애 순환 생명 복의 퍼옴 습진  
1                             Topic4

토픽을 봤을 때 정상적으로 분류가 되지 않는 것 같음.